## Vector
Vectors have values of the **same type**, and consists of **one dimensional** data.

In [ ]:
(c(c(1,2,3), c(4,5,6))) # nested columns are collapsed

In [ ]:
c(1,"blah", TRUE) # vector with different types will be coerced to the same type

## List
Lists have values of the **different type**, and consists of **one dimensional** data.

In [ ]:
list(1,"blah", TRUE, c('a','b','c','d')) # a list will preserve types

In [ ]:
c(list('a','b'), list('c','d')) # vector of lists is collapsed into a single list

In [ ]:
list(col=c(1,2,3), num=5, nested=list('nested','list')) # Creating a list with named indices

In [ ]:
l <- list(c(1,2,3), 5, list('nested','list')) # Creating a list
names(l) <- c("col", "num", "nested") # assign names later
l

In [ ]:
la <- append(l, list(new=3)) # appending elements to a list, more like merging two lists
lb <- c(l, list(new=3)) # same thing

print(paste("la and lb are", ifelse(identical(la, lb), "identical", "different")))
la

In [ ]:
la$new # access named element

## Matrix
Matrices have values of the **same type**, and consists of **two dimensional** data.

In [ ]:
m <- matrix(c(1:10), nrow=2)
m

## Array
Arrays have values of the **same type**, and consists of **multiple dimensional** data.

In [30]:
a <- array(c(1,2,3,4,5,6,7,8,9,10,11,12), dim=c(3,4)) # add dimension to a vector
attributes(a) # retrieve the attributes of an array
# dim(a)

$dim
[1] 3 4

In [43]:
dim(a) = c(2,6) # can reshape an array
a

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11  
[2,] 2    4    6    8    10   12

In [45]:
is.matrix(a) # a two-dimensional array is just a matrix

[1] TRUE

In [46]:
typeof(a) # type of the array is the type of the contained element

[1] "double"

In [39]:
# Try to create an array with less size than data
# dim(a) = c(1,2) # an error because dimension not matching
a2 <- array(c(1,2,3,4,5,6,7,8,9,10,11,12), dim=c(1,2)) # when creating, rest of the values get truncated
a2

[,1] [,2]
[1,] 1    2

In [54]:
# Try to create an array with larger size than data
# dim(a) <- c(9,9) # an error: ... dims [product 81] do not match the length of object [12]
a3 <- array(c(1,2,3,4,5,6,7,8,9,10,11,12), dim=c(9,9)) # when creating, values are repeated
a3

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,] 1    10    7    4   1    10    7    4   1   
 [2,] 2    11    8    5   2    11    8    5   2   
 [3,] 3    12    9    6   3    12    9    6   3   
 [4,] 4     1   10    7   4     1   10    7   4   
 [5,] 5     2   11    8   5     2   11    8   5   
 [6,] 6     3   12    9   6     3   12    9   6   
 [7,] 7     4    1   10   7     4    1   10   7   
 [8,] 8     5    2   11   8     5    2   11   8   
 [9,] 9     6    3   12   9     6    3   12   9

In [56]:
a3 <- array(c(1:12), dim=c(2,3,2)) # array of multiple dimension
dim(a3)

[1] 2 3 2

In [58]:
is.matrix(a3) # not a matrix

[1] FALSE

## Array
Arrays have values of the **xxx type**, and consists of **xxx dimensional** data.

## dplyr library

In [71]:
flights %>% group_by(hour) %>% filter(!is.na(dep_delay)) %>% summarise(dep_delay  = mean(dep_delay))

hour dep_delay 
1   5    0.6877572
2   6    1.6427956
3   7    1.9140778
4   8    4.1279478
5   9    4.5837378
6  10    6.4982946
7  11    7.1916503
8  12    8.6148485
9  13   11.4376504
10 14   13.8188742
11 15   16.8945646
12 16   18.7570165
13 17   21.1006059
14 18   21.1100818
15 19   24.7847911
16 20   24.3041048
17 21   24.1957431
18 22   18.7910972
19 23   14.0171756